drop table AUTHORITIES if exists
drop table REPLAYMATCH if exists
drop table REPLAYUNIT if exists
drop table REPLAYWORD if exists
drop table USERS if exists
create table AUTHORITIES (AUTHORITY varchar(255) not null, username varchar(255), primary key (AUTHORITY))
create table REPLAYMATCH (matchid integer generated by default as identity, botpoints integer, date timestamp, humanpoints integer, win boolean, USERNAME varchar(255), primary key (matchid))
create table REPLAYUNIT (replayunitid integer generated by default as identity, col integer not null, letter integer not null, row integer not null, replaywordid integer, primary key (replayunitid))
create table REPLAYWORD (replaywordid integer generated by default as identity, date timestamp, human boolean not null, score integer not null, matchid integer, primary key (replaywordid))
create table USERS (USERNAME varchar(255) not null, AGE integer, ENABLED boolean not null, NAME varchar(255), PASSWORD varchar(255) not null, primary key (USERNAME))
alter table AUTHORITIES add constraint FKl8gm1dxqhdixkdsm1p7er9c21 foreign key (USERNAME) references USERS
alter table REPLAYMATCH add constraint FK4e9drmwg9h9rdoamubd2nxo5p foreign key (USERNAME) references USERS
alter table REPLAYUNIT add constraint FKg2kwfvloli08mtthutmbhunlj foreign key (replaywordid) references REPLAYWORD
alter table REPLAYWORD add constraint FKdgx0ofjh2rs9txnj6wk5au907 foreign key (matchid) references REPLAYMATCH